workspace:
  base: /go
  path: src/toroid.io/drone-plugins/drone-kicad

pipeline:
  buildgo:
    image: golang
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  scripts:
    image: bravissimolabs/alpine-git
    commands:
      - git clone https://github.com/Toroid-io/kicad-ci-scripts
      - git clone https://github.com/yaqwsx/PcbDraw
    when:
      branch: master

  publish:
    image: plugins/docker
<<<<<<< HEAD
    repo: surgecloud/drone-kicad
    tags: [latest]
=======
    repo: toroid/drone-kicad
    tags: [latest, 0.5.5]
>>>>>>> upstream/master
    when:
      branch: master
    secrets: [docker_username, docker_password]

  publish-test:
    image: plugins/docker
    repo: surgecloud/drone-kicad
    tags: ${DRONE_DEPLOY_TO}
    when:
      event: deployment
      environment:
        exclude: production
    secrets: [docker_username, docker_password]
